function time_penalty = CommThruNetwork(comm_net)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

%Status Quo Network - Deterministic Communication


comm_seq={...
    'Director','Supervisor.A';...
    'Supervisor.A','Machine.A1';...
    'Machine.A1','Receiving';...
    'Receiving','Machine.A1';...
    'Machine.A1','Supervisor.A';...
    'Supervisor.A','Director';...
    'Director','Supervisor.B';...
    'Supervisor.B','Machine.B1';...
    'Machine.B1','Receiving';...
    'Receiving','Machine.B1';...
    'Machine.B1','Supervisor.B';...
    'Supervisor.B','Director';...
    'Director','Supervisor.C';...
    'Supervisor.C','Machine.C1';...
    'Machine.C1','Receiving';...
    'Receiving','Machine.C1';...
    'Machine.C1','Supervisor.C';...
    'Supervisor.C','Director';...
    };
    
    
end

