function time_penalty = CommThruNetwork(comm_net)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

%Status Quo Network - Deterministic Communication
comm_seq={...
    'Director','Supervisor.A';...
    'Supervisor.A','Machine.A1';...
    'Machine.A1','Receiving';...
    'Receiving','Machine.A1';...
    'Machine.A1','Supervisor.A';...
    'Supervisor.A','Director';...
    'Director','Supervisor.B';...
    'Supervisor.B','Machine.B1';...
    'Machine.B1','Receiving';...
    'Receiving','Machine.B1';...
    'Machine.B1','Supervisor.B';...
    'Supervisor.B','Director';...
    'Director','Supervisor.C';...
    'Supervisor.C','Machine.C1';...
    'Machine.C1','Receiving';...
    'Receiving','Machine.C1';...
    'Machine.C1','Supervisor.C';...
    'Supervisor.C','Director';...
    };

%Director/Receiving Centric - deterministic
comm_seq={...
    'Director','Supervisor.A';...
    'Supervisor.A','Machine.A1';...
    'Machine.A1','Receiving';...
    'Receiving','Machine.A1';...
    'Machine.A1','Supervisor.A';...
    'Supervisor.A','Director';...
    'Director','Supervisor.B';...
    'Supervisor.B','Machine.B1';...
    'Machine.B1','Receiving';...
    'Receiving','Machine.B1';...
    'Machine.B1','Supervisor.B';...
    'Supervisor.B','Director';...
    'Director','Supervisor.C';...
    'Supervisor.C','Machine.C1';...
    'Machine.C1','Receiving';...
    'Receiving','Machine.C1';...
    'Machine.C1','Supervisor.C';...
    'Supervisor.C','Director';...
    };

%ERP centric - deterministic
comm_seq={...
    'Director','ERP';...
    'Supervisor.A','ERP';...
    'Supervisor.A','Machine.A1';...
    'Receiving','ERP';...
    'Machine.A1','ERP';...
    'Supervisor.A','ERP';...
    'Supervisor.B','ERP';...
    'Supervisor.B','Machine.B1';...
    'Receiving','ERP';...
    'Machine.B1','ERP';...
    'Supervisor.B','ERP';...
    'Supervisor.C','ERP';...
    'Supervisor.C','Machine.C1';...
    'Receiving','ERP';...
    'Machine.C1','ERP';...
    'Supervisor.C','ERP';...
    };


   
time_penalty=0;
for i=1:length(comm_seq)
    [temp dist]=shortestpath(comm_net,comm_seq(i,1),comm_seq(i,2));
    time_penalty=dist+time_penalty;
end
    
end

